install! 'cocoapods', :warn_for_unused_master_specs_repo => false
platform :ios, '11.0'

target 'DTCoreComponents' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Amplitude'
  pod 'AppCenter'
  pod 'AppsFlyerFramework'
  pod 'FBSDKCoreKit'
  pod 'Firebase/Analytics'
  pod 'Firebase/RemoteConfig'
  pod 'KeychainAccess'
  pod 'TPInAppReceipt'
  pod 'YandexMobileMetrica'

end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
